# Generated by Django 4.1.4 on 2023-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkingName', models.CharField(max_length=100)),
                ('parkingAddress', models.CharField(max_length=100)),
                ('parkingPhone', models.CharField(max_length=100)),
                ('parkingCapacity', models.CharField(max_length=100)),
                ('parkingPrice', models.CharField(max_length=100)),
            ],
        ),
    ]
