# Generated by Django 4.1.4 on 2023-01-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
