# Generated by Django 4.1.4 on 2023-01-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('montant', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
    ]
