# Generated by Django 4.1.4 on 2023-01-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='period',
            new_name='periode',
        ),
    ]
